spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/paragraphs}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
        format_sql: true
    open-in-view: false
    show-sql: true
    generate-ddl: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  servlet:
    multipart:
      max-file-size=1MB

server:
  port: 8080